const hotelData = [
  {
    date: new Date(),
    band: "abc",
    city: "New York",
    state: "Washington",
    king: 2,
    twin: 4,
    suite: 0,
    roomNightTotal: 6,
    spend: 774,
    roomMarketAverage: 187,
    savings: 348,
  },
  {
    date: new Date(),
    band: "efg",
    city: "Austin",
    state: "Oregon",
    king: 2,
    twin: 4,
    suite: 0,
    roomNightTotal: 6,
    spend: 900,
    roomMarketAverage: 195,
    savings: 270,
  },
  {
    date: new Date(),
    band: "xyz",
    city: "Seattle",
    state: "California",
    king: 2,
    twin: 4,
    suite: 0,
    roomNightTotal: 6,
    spend: 873,
    roomMarketAverage: 200,
    savings: 327,
  },
  {
    date: new Date(),
    band: "xyz",
    city: "Detroit",
    state: "Arizona",
    king: 2,
    twin: 4,
    suite: 0,
    roomNightTotal: 6,
    spend: 873,
    roomMarketAverage: 200,
    savings: 327,
  },
  {
    date: new Date(),
    band: "xyz",
    city: "San Franciso",
    state: "Texas",
    king: 2,
    twin: 4,
    suite: 0,
    roomNightTotal: 6,
    spend: 873,
    roomMarketAverage: 200,
    savings: 327,
  },
  {
    date: new Date(),
    band: "xyz",
    city: "Los Angeles",
    state: "Tennessee",
    king: 2,
    twin: 4,
    suite: 0,
    roomNightTotal: 6,
    spend: 873,
    roomMarketAverage: 200,
    savings: 327,
  },
];

export default hotelData;
